# Generated by Django 6.0.6 on 2026-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя рассылка"
            ),
        ),
    ]
